name: ForestVPNAPI
targets:
  ForestVPNAPI:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [ForestVPNAPIClient/Classes]
    info:
      path: ./Info.plist
      version: 2.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
