//
// AppleAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AppleAPI {

    /**
     App store receipt verification
     
     - parameter appStoreReceiptVerificationRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func verifyAppStoreReceipt(appStoreReceiptVerificationRequest: AppStoreReceiptVerificationRequest, apiResponseQueue: DispatchQueue = ForestVPNAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) {
        verifyAppStoreReceiptWithRequestBuilder(appStoreReceiptVerificationRequest: appStoreReceiptVerificationRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     App store receipt verification
     - POST /purchase/apple/verify/
     - BASIC:
       - type: http
       - name: bearerAuth
     - parameter appStoreReceiptVerificationRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func verifyAppStoreReceiptWithRequestBuilder(appStoreReceiptVerificationRequest: AppStoreReceiptVerificationRequest) -> RequestBuilder<Void> {
        let localVariablePath = "/purchase/apple/verify/"
        let localVariableURLString = ForestVPNAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appStoreReceiptVerificationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ForestVPNAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
