//
// GoogleAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GoogleAPI {

    /**
     Play store purchase verification
     
     - parameter playStorePurchaseVerificationRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func verifyPlayStorePurchase(playStorePurchaseVerificationRequest: PlayStorePurchaseVerificationRequest, apiResponseQueue: DispatchQueue = ForestVPNAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) {
        verifyPlayStorePurchaseWithRequestBuilder(playStorePurchaseVerificationRequest: playStorePurchaseVerificationRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Play store purchase verification
     - POST /purchase/google/verify/
     - BASIC:
       - type: http
       - name: bearerAuth
     - parameter playStorePurchaseVerificationRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func verifyPlayStorePurchaseWithRequestBuilder(playStorePurchaseVerificationRequest: PlayStorePurchaseVerificationRequest) -> RequestBuilder<Void> {
        let localVariablePath = "/purchase/google/verify/"
        let localVariableURLString = ForestVPNAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playStorePurchaseVerificationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ForestVPNAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
