//
// AppStoreReceiptVerificationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppStoreReceiptVerificationRequest: Codable, Hashable {

    /** The latest Base64-encoded transaction receipt. */
    public var receipt: Data
    public var price: Int64?
    public var currency: String?

    public init(receipt: Data, price: Int64? = nil, currency: String? = nil) {
        self.receipt = receipt
        self.price = price
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case receipt
        case price
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(receipt, forKey: .receipt)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

