//
// ConnectionMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConnectionMode: Codable, Hashable {

    public var id: UUID?
    public var name: String?
    public var description: String?
    public var icon: String?

    public init(id: UUID? = nil, name: String? = nil, description: String? = nil, icon: String? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case icon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(icon, forKey: .icon)
    }
}

