//
// Country.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Country: Codable, Hashable {

    public var id: String
    public var name: String
    public var emoji: String
    public var alternativeNames: [String]?

    public init(id: String, name: String, emoji: String, alternativeNames: [String]? = nil) {
        self.id = id
        self.name = name
        self.emoji = emoji
        self.alternativeNames = alternativeNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case emoji
        case alternativeNames = "alternative_names"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(emoji, forKey: .emoji)
        try container.encodeIfPresent(alternativeNames, forKey: .alternativeNames)
    }
}

