//
// CreateOrUpdatePortForwardingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrUpdatePortForwardingRequest: Codable, Hashable {

    public var dstPort: Int?

    public init(dstPort: Int? = nil) {
        self.dstPort = dstPort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dstPort = "dst_port"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dstPort, forKey: .dstPort)
    }
}

