//
// Environment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Environment: Codable, Hashable {

    public var id: UUID
    public var name: String
    public var apiBaseUrl: String

    public init(id: UUID, name: String, apiBaseUrl: String) {
        self.id = id
        self.name = name
        self.apiBaseUrl = apiBaseUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case apiBaseUrl = "api_base_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(apiBaseUrl, forKey: .apiBaseUrl)
    }
}

