//
// FCMDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FCMDevice: Codable, Hashable {

    public var registrationId: String
    public var deviceId: String?
    public var active: Bool
    public var createdAt: Date

    public init(registrationId: String, deviceId: String? = nil, active: Bool, createdAt: Date) {
        self.registrationId = registrationId
        self.deviceId = deviceId
        self.active = active
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case registrationId = "registration_id"
        case deviceId = "device_id"
        case active
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(registrationId, forKey: .registrationId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encode(active, forKey: .active)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

