//
// Friendship.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Friendship: Codable, Hashable {

    public var id: UUID
    public var user: User?
    public var createdAt: Date

    public init(id: UUID, user: User? = nil, createdAt: Date) {
        self.id = id
        self.user = user
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

