//
// NetworkService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NetworkService: Codable, Hashable {

    public enum Proto: String, Codable, CaseIterable {
        case wireguard = "wireguard"
    }
    public var proto: Proto
    public var connectionUri: String

    public init(proto: Proto, connectionUri: String) {
        self.proto = proto
        self.connectionUri = connectionUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proto
        case connectionUri = "connection_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(proto, forKey: .proto)
        try container.encode(connectionUri, forKey: .connectionUri)
    }
}

