//
// UpdateFCMDeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateFCMDeviceRequest: Codable, Hashable {

    public var deviceId: String?
    public var active: Bool?

    public init(deviceId: String? = nil, active: Bool? = nil) {
        self.deviceId = deviceId
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceId = "device_id"
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(active, forKey: .active)
    }
}

