//
// WireGuard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WireGuard: Codable, Hashable {

    public var id: UUID
    public var privKey: String
    public var pubKey: String
    public var peers: [WireGuardPeer]

    public init(id: UUID, privKey: String, pubKey: String, peers: [WireGuardPeer]) {
        self.id = id
        self.privKey = privKey
        self.pubKey = pubKey
        self.peers = peers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case privKey = "priv_key"
        case pubKey = "pub_key"
        case peers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(privKey, forKey: .privKey)
        try container.encode(pubKey, forKey: .pubKey)
        try container.encode(peers, forKey: .peers)
    }
}

