//
// WireGuardPeerUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WireGuardPeerUser: Codable, Hashable {

    public var id: UUID?
    public var username: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var photoUrl: String?

    public init(id: UUID? = nil, username: String? = nil, firstName: String? = nil, lastName: String? = nil, email: String? = nil, photoUrl: String? = nil) {
        self.id = id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.photoUrl = photoUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case photoUrl = "photo_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(photoUrl, forKey: .photoUrl)
    }
}

